apiVersion: v1
kind: Service
metadata:
  name: {{ include "django-sample.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: {{ include "django-sample.name" . }}